language: python
cache:
    pip: true
    directories:
        - $HOME/.npm
        - node_modules
git:
    depth: 20

matrix:
    include:
        - os: linux
          python: "2.7"
          env: UNIT_TEST=true
        - os: linux
          python: "2.7"
          env: DEBUGGER_TEST_RELEASE=true
        - os: linux
          python: "2.7"
          env: SINGLE_WORKSPACE_TEST=true
        - os: linux
          python: "2.7"
          env: MULTIROOT_WORKSPACE_TEST=true
        - os: linux
          python: "3.6-dev"
          env: DEBUGGER_TEST_RELEASE=true
        - os: linux
          python: "3.6-dev"
          env: SINGLE_WORKSPACE_TEST=true
        - os: linux
          python: "3.6-dev"
          env: MULTIROOT_WORKSPACE_TEST=true
        - os: linux
          python: "3.6-dev"
          env: PERFORMANCE_TEST=true
        - os: linux
          python: "3.7-dev"
          env: DEBUGGER_TEST_RELEASE=true
        - os: linux
          python: "3.7-dev"
          env: SINGLE_WORKSPACE_TEST=true
        - os: linux
          python: "3.7-dev"
          env: MULTIROOT_WORKSPACE_TEST=true
        - os: linux
          python: "3.7-dev"
          env: BUNDLE=true
        - os: linux
          python: "3.7-dev"
          env: FUNCTIONAL_TEST=true
before_install: |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi
  git clone https://github.com/creationix/nvm.git ./.nvm
  source ./.nvm/nvm.sh
  nvm install 8.9.1
  nvm use 8.9.1
  npm install npm@latest -g
  npm install -g vsce
  export CI_PYTHON_PATH=`which python`
install:
  - travis_wait 5 npm ci
  - npm run clean
  - npx gulp prePublishNonBundle
  - python -m pip install --upgrade 'pip<19'
  - python -m pip install --upgrade -r ./build/test-requirements.txt
  - npx gulp installPythonLibs

script:
  - if [ $UNIT_TEST == "true" ]; then
        npx gulp hygiene-modified;
        npm run cover:enable;
        npm run test:unittests:cover;
    fi
  - if [[ $BUNDLE == "true" && $AZURE_STORAGE_ACCOUNT ]]; then
        npm run clean;
        npm run updateBuildNumber -- --buildNumber $TRAVIS_BUILD_NUMBER
        npm run package;
        npx gulp clean:cleanExceptTests;
        npm run testSmoke;
    fi
